### ISSUE TITLE
Fix nav menu on the homepage @ < 1057px widths

### ISSUE THREAD

**Issue by camerican** [christov44/Portfolio_Baker#2]
On the homepage, the .tag_line overlaps with the navigation menu at widths less than 1057 pixels, making it impossible to click through to desired pages.  One quick fix would be to give the nav a z-index value greater than 1, which would move the navigation on top of the .tag_line.  Ideally, you wouldn't want the navigation to be pushed down below the .page_title_bar area.

**Comment by christov44** [comment]
I tried adding z-index values to the nav in my css and nothing changed. So I set a min width for the entire body and that fixed it!
